-- KDS v3 phase 2 — Path A bump: raise grid_rows/grid_cols max from 12 to 24
--
-- Spec: https://linear.app/mokesai/issue/MOK-152
-- Plan: .planning/kds-v3/PHASE-2-PLAN.md (T-A — 2026-05-12)
--
-- The original phase 2 schema (20260512015358) capped grid_rows and grid_cols
-- at 12. After seeing the rendered editor, the operator surfaced two desired
-- capabilities — variable column heights and finer per-box height adjustment —
-- that are both expressible by raising the grid resolution rather than
-- changing the data model. A 24x24 grid lets the operator simulate columns
-- with 1/2/3 rows by spanning 24 / 12 / 8 rows respectively, and gives ~2x
-- finer height adjustment.
--
-- Postgres can't ALTER an existing CHECK in place — DROP + ADD is required.
-- Constraint names were auto-generated by Postgres for inline CHECKs in T1
-- and are deterministic: <table>_<column>_check. Verified against the dev
-- database (cafe-pulse-dev / ettmabcwfhidcpapphgm) on 2026-05-12.
--
-- Rollback step lives in .planning/kds-v3/PHASE-2-ROLLBACK.sql (alongside the
-- T1 rollback, since both migrations are reverted as one unit when phase 2
-- is abandoned).

BEGIN;

ALTER TABLE public.kds_screens
  DROP CONSTRAINT IF EXISTS kds_screens_grid_rows_check,
  DROP CONSTRAINT IF EXISTS kds_screens_grid_cols_check;

ALTER TABLE public.kds_screens
  ADD CONSTRAINT kds_screens_grid_rows_check CHECK (grid_rows BETWEEN 1 AND 24),
  ADD CONSTRAINT kds_screens_grid_cols_check CHECK (grid_cols BETWEEN 1 AND 24);

COMMIT;
